# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/view.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 761)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PairList = QtWidgets.QListWidget(self.centralwidget)
        self.PairList.setObjectName("PairList")
        self.horizontalLayout.addWidget(self.PairList, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.Graph = QtWidgets.QScrollArea(self.centralwidget)
        self.Graph.setWidgetResizable(True)
        self.Graph.setObjectName("Graph")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 528, 608))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Graph.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.Graph)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.Prev = QtWidgets.QPushButton(self.centralwidget)
        self.Prev.setObjectName("Prev")
        self.horizontalLayout1.addWidget(self.Prev)
        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setObjectName("Next")
        self.horizontalLayout1.addWidget(self.Next)
        self.verticalLayout.addLayout(self.horizontalLayout1)
        self.plotButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotButton.setObjectName("plotButton")
        self.verticalLayout.addWidget(self.plotButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuLoad_from_npy = QtWidgets.QMenu(self.menuFile)
        self.menuLoad_from_npy.setObjectName("menuLoad_from_npy")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionchoose_file = QtWidgets.QAction(MainWindow)
        self.actionchoose_file.setObjectName("actionchoose_file")
        self.actionchoose_dir = QtWidgets.QAction(MainWindow)
        self.actionchoose_dir.setObjectName("actionchoose_dir")
        self.actionLoad_from_hdf5 = QtWidgets.QAction(MainWindow)
        self.actionLoad_from_hdf5.setObjectName("actionLoad_from_hdf5")
        self.actionAdd_timeline = QtWidgets.QAction(MainWindow)
        self.actionAdd_timeline.setObjectName("actionAdd_timeline")
        self.actionAdd_pairs = QtWidgets.QAction(MainWindow)
        self.actionAdd_pairs.setObjectName("actionAdd_pairs")
        self.actionAdd_data = QtWidgets.QAction(MainWindow)
        self.actionAdd_data.setObjectName("actionAdd_data")
        self.actionAdd_data_2 = QtWidgets.QAction(MainWindow)
        self.actionAdd_data_2.setObjectName("actionAdd_data_2")
        self.actionAdd_timelne = QtWidgets.QAction(MainWindow)
        self.actionAdd_timelne.setObjectName("actionAdd_timelne")
        self.actionAdd_data_in_csv = QtWidgets.QAction(MainWindow)
        self.actionAdd_data_in_csv.setObjectName("actionAdd_data_in_csv")
        self.menuLoad_from_npy.addAction(self.actionAdd_pairs)
        self.menuLoad_from_npy.addAction(self.actionAdd_data)
        self.menuFile.addAction(self.menuLoad_from_npy.menuAction())
        self.menuFile.addAction(self.actionLoad_from_hdf5)
        self.menuFile.addAction(self.actionAdd_data_in_csv)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "TextLabel"))
        self.Prev.setText(_translate("MainWindow", "<"))
        self.Next.setText(_translate("MainWindow", ">"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuLoad_from_npy.setTitle(_translate("MainWindow", "Load from .npy"))
        self.actionchoose_file.setText(_translate("MainWindow", "choose file"))
        self.actionchoose_dir.setText(_translate("MainWindow", "choose dir"))
        self.actionLoad_from_hdf5.setText(_translate("MainWindow", "Load from .hdf5"))
        self.actionAdd_timeline.setText(_translate("MainWindow", "Add timeline"))
        self.actionAdd_pairs.setText(_translate("MainWindow", "Add pairs"))
        self.actionAdd_data.setText(_translate("MainWindow", "Add data"))
        self.actionAdd_data_2.setText(_translate("MainWindow", "Add data"))
        self.actionAdd_timelne.setText(_translate("MainWindow", "Add timelne"))
        self.actionAdd_data_in_csv.setText(_translate("MainWindow", "Add data in .csv"))

